spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/kakaopay?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    # prod 환경에서는 해당 값 secret value
    password: ${KAKAOPAY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: ${KAKAOPAY_RABBITMQ_PASSWORD}
    listener:
      simple:
        prefetch: 1
        concurrency: 2

springdoc:
  swagger-ui:
    enabled: true

server:
  shutdown: graceful
  servlet:
    context-path: /v1

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

---
api:
  reward-internal:
    base-url: http://localhost:8090
    username: kakaopay
    password: ${REWARD_INTERNAL_API_BASIC_AUTH_PASSWORD}

rabbit-mq:
  exchange: message-queue-exchange
  advertisement-participation-message-queue:
    name: advertisement-participation-message-queue
    routing-key: advertisement-participation-message-key
